### ISSUE TITLE
Oracle JDBC driver wont work

### ISSUE THREAD

**Issue by stormsw** [stormsw/docker-wildfly#1]
Drivers integrated to this image (ojdbc6.jar and ojdbc7.jar) produces connection error, with strange complain on connection URL

**Comment by stormsw** [comment]
Everything works on host if copied from container

``` shell
sudo docker cp <containerId>:/opt/jboss/wildfly /tmp/wildfly-from-container
```

There is a log produced with ojdbc7_g.jar driver:

```
    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:759)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_40]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_40]
    at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_40]
Caused by: java.sql.SQLException: ORA-00604: error occurred at recursive SQL level 1
ORA-01882: timezone region not found

    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:461)
    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:394)
    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:386)
    at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1039)
    at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:481)
    at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:681)
    at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:256)
    at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:414)
    at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:877)
    at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:664)
    at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:721)
    at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:415)
    at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:26)
    at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:597)
    at org.jboss.jca.adapters.jdbc.local.LocalManagedConnectionFactory.createLocalManagedConnection(LocalManagedConnectionFactory.java:322) [ironjacamar-jdbc-1.1.9.Final.jar:1.1.9.Final]
    ... 30 more
```

**Comment by stormsw** [comment]
I modified .../bin/standalone.conf, to include this option for jvm initialization.
Setting environment variable TZ haven't effect for me.

```
-Duser.timezone=UTC+02:00
```

**Comment by stormsw** [comment]
![screenshot from 2015-04-07 20 07 00](https://cloud.githubusercontent.com/assets/479564/7028882/b4db0414-dd61-11e4-835a-8e78a98ebfbf.png)

**Comment by stormsw** [comment]
Related issue [https://github.com/docker/docker/issues/3359]

**Comment by mdopp** [comment]
a simple patch would be to change the defaultConnectionProperties.properties inside the jar file.

> oracle.jdbc.timezoneAsRegion=false

[defaultConnectionProperties.properties.zip](https://github.com/stormsw/docker-wildfly/files/351073/defaultConnectionProperties.properties.zip)
